/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SwapRouteImport } from './routes/swap'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as LiquidityRouteImport } from './routes/liquidity'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ChainsChainKeyRouteImport } from './routes/chains.$chainKey'

const SwapRoute = SwapRouteImport.update({
  id: '/swap',
  path: '/swap',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const LiquidityRoute = LiquidityRouteImport.update({
  id: '/liquidity',
  path: '/liquidity',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ChainsChainKeyRoute = ChainsChainKeyRouteImport.update({
  id: '/chains/$chainKey',
  path: '/chains/$chainKey',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/liquidity': typeof LiquidityRoute
  '/settings': typeof SettingsRoute
  '/swap': typeof SwapRoute
  '/chains/$chainKey': typeof ChainsChainKeyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/liquidity': typeof LiquidityRoute
  '/settings': typeof SettingsRoute
  '/swap': typeof SwapRoute
  '/chains/$chainKey': typeof ChainsChainKeyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/liquidity': typeof LiquidityRoute
  '/settings': typeof SettingsRoute
  '/swap': typeof SwapRoute
  '/chains/$chainKey': typeof ChainsChainKeyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/liquidity'
    | '/settings'
    | '/swap'
    | '/chains/$chainKey'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/liquidity'
    | '/settings'
    | '/swap'
    | '/chains/$chainKey'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/liquidity'
    | '/settings'
    | '/swap'
    | '/chains/$chainKey'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  LiquidityRoute: typeof LiquidityRoute
  SettingsRoute: typeof SettingsRoute
  SwapRoute: typeof SwapRoute
  ChainsChainKeyRoute: typeof ChainsChainKeyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/swap': {
      id: '/swap'
      path: '/swap'
      fullPath: '/swap'
      preLoaderRoute: typeof SwapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/liquidity': {
      id: '/liquidity'
      path: '/liquidity'
      fullPath: '/liquidity'
      preLoaderRoute: typeof LiquidityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chains/$chainKey': {
      id: '/chains/$chainKey'
      path: '/chains/$chainKey'
      fullPath: '/chains/$chainKey'
      preLoaderRoute: typeof ChainsChainKeyRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  LiquidityRoute: LiquidityRoute,
  SettingsRoute: SettingsRoute,
  SwapRoute: SwapRoute,
  ChainsChainKeyRoute: ChainsChainKeyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
